KERNEL_SIZE: 201
image_size: [256, 256, 3]
primary_samples: 1000
backup_samples: 4000
num_epochs: 2001
densification_interval: 300
learning_rate: 0.01
image_file_name: "Illusion.png"
display_interval: 100
gradient_threshold: 0.005
gaussian_threshold: 0.002
display_loss: False
