KERNEL_SIZE: 201
image_size: [1024, 1024, 3]
primary_samples: 1000
backup_samples: 4000
num_epochs: 1001
densification_interval: 300
learning_rate: 0.01
image_file_name: "Illusion.png"
display_interval: 100
gradient_threshold: 0.002
gaussian_threshold: 0.005
display_loss: False
